version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Run danger
          command: npm run danger
      
      - run:
          name: Build
          command: npm run build

      - run:
          name: lint
          command: |
            mkdir -p /tmp/test-reports/eslint
            node_modules/.bin/eslint . --format junit --output-file /tmp/test-reports/eslint/results.xml

      - store_test_results:
          path: /tmp/test-reports
