version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - checkout

      - run:
          name: Build
          command: npm run build

      - run:
          name: Run danger
          command: npm run danger
